### ISSUE TITLE
Unable to use when running as service

### ISSUE THREAD

**Issue by inukiwi** [hensm/node-ddcci#6]
When I'm trying to get the monitor list while running my script as a Windows service I'm getting the following error:

`...\node_modules\@hensm\ddcci\node_modules\bindings\bindings.js:88
        throw e
        ^

Error: Failed to get number of physical monitors
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (...\node_modules\@hensm\ddcci\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (...\node_modules\@hensm\ddcci\index.js:3:34)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)`

Running the script manually works fine. Is there something extra I should do to be able to use it in a service? I'm using node-windows to create the service.

**Comment by hensm** [comment]
I suspect it has something to do with the service running in a different session. [`EnumDisplayDevices`](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-enumdisplaydevicesa) gets info for the display devices in the current session:  
> The operating system identifies each display device in the current session with an index value. The index values are consecutive integers, starting at 0. [...].

I'm not sure if there's a way to access display devices from session 0. Probably not possible to run this as a service unless the service can be run in the user session, though I don't think that's possible either.

Can't test anything right now since I'm away from my Windows machine.
